spring:
  application:
    name: gateway_filter
  profiles:
    active: elapsed_route

server:
  port: 10011

---
spring:
  profiles: add_request_header_route
  cloud:
    gateway:
      routes:
        - id: add_request_header_route
          uri: http://httpbin.org:80/get
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]

---
spring:
  profiles: elapsed_route
  cloud:
    gateway:
      routes:
        - id: elapsed_route
          uri: http://httpbin.org:80/get
          filters:
            - RequestTime=true
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
