server:
  port: 10004

spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:localhost:9002/eureka/